development: &default
  adapter: postgis
  encoding: UTF8
  database: greencarelabs_gis
  pool: 5
  username: postgres
  password: esf823r
  timeout: 5000
  schema_search_path: "public,postgis"
  script_dir: /Applications/Postgres.app/Contents/Versions/9.3/share/postgresql/contrib/postgis-2.1

production:
  adapter: postgis
  encoding: UTF8
  database: greencarelabs_production
  password: esf823r
  username: deploy
  pool: 5
  timeout: 5000
  schema_search_path: "public,postgis"
  script_dir: /usr/share/postgresql/9.3/contrib/postgis-2.1